### ISSUE TITLE
working with MSS425F but only to turn all on / off

### ISSUE THREAD

**Issue by aaamoeder** [dehsgr/node-red-contrib-meross#10]
as the title says, it's working but it turns the entire 4socket/usb combo on or off but I'd like to be able to individually turn them off or on as I can do in the app

Have tried multiple configs, but no go.

**Comment by dehsgr** [comment]
You might provide me with sniffed infos/payloads getting/setting values one by one. As I haven’t such device I cannot directly implement this without some help.

**Comment by aaamoeder** [comment]
![meross](https://user-images.githubusercontent.com/20947118/117180945-034dc600-add5-11eb-8de7-d25468ac7298.PNG)

Seems like the only thing that's changing is the channel (0 for all on or off, then 1-4 for the 4 sockets and 5 for the usb ports)

![2meross](https://user-images.githubusercontent.com/20947118/117181738-d8b03d00-add5-11eb-852c-e99c73161942.PNG)

**Comment by aaamoeder** [comment]
any way I could send a msg.channel or something to choose the right one ?

**Comment by dehsgr** [comment]
I‘ll take a look on that soon. Currently I‘m a bit busy. Thanks for your understanding.

**Comment by dehsgr** [comment]
Hi @aaamoeder,

You might update your module using this repository as source. Afterwards you should be able to set specific channel via msg.channel attribute.

I would like you to confirm it is working and this is implemented as you expected. If you confirm, I would publish these changes to NPM afterwards.

Thank you!

**Comment by aaamoeder** [comment]
Used your changes and now it works !!! thanks a million for your quick response !

**Comment by dehsgr** [comment]
Thanks for your feedback. I just published these changes to NPM.

**Comment by aaamoeder** [comment]
Just FYI, when I try to use the get state node now it reports 
```payload: "Received unexpected data!"```

**Comment by dehsgr** [comment]
@aaamoeder it should be working again after updating to v1.3.1.

**Comment by aaamoeder** [comment]
> @aaamoeder it should be working again after updating to v1.3.1.

yup, working perfectly ! thanks for the quick work from my wife and I ;-)
