### ISSUE TITLE
sniffing

### ISSUE THREAD

**Issue by Nicco02F** [dehsgr/node-red-contrib-meross#12]
There is an easier way to find tokens and ids:

-npm i anyproxy

-run anyproxy

-connect to <your ip(where anyproxy running>:8002 and click in rootCA, scan code or download certificate and install in your phone

-In your phone go to the wifi settings and set the proxy with ip (your computer) and port 8001

use the meross's app and find the credentials

**Comment by dehsgr** [comment]
Thank you for posting this additional way of sniffing!

**Comment by ghost** [comment]
That is my first account, tanks to you
