### ISSUE TITLE
MSS210-Mini Connection Dropped All Requests - Content-Length Header Case Issue

### ISSUE THREAD

**Issue by peterchs** [dehsgr/node-red-contrib-meross#13]
Recently purchased some Meross MSS210-Mini smartplugs
https://www.amazon.co.uk/gp/product/B08D69M19G

These would refuse to work with the current version of the module, with the the connection being dropped immediately after all requests, no response returned.

After a lot of debugging I managed to identify this is due to the new plugs being case sensitive to the content length header.  By default the request lib sends 'content-length', when this is altered to 'Content-Length' the device responds.  I've altered the code to manually calculate/insert this header with the case as the device prefers it.

I have tested this against my new MSS210-Mini devices and my older big MSS210 with its original firmware and on/off/status functions are working as expected.  Interestingly the older device is working regardless of the case of content-length its just these new devices which are picky about the case.

I'll raise a PR with these changes.

**Comment by peterchs** [comment]
PR https://github.com/dehsgr/node-red-contrib-meross/pull/14 fixes this issue

**Comment by dehsgr** [comment]
Published new version to NPM.

**Comment by dehsgr** [comment]
There were heavy changes within API resulting in static message ids, sign tokens and timestamp not being accepted anymore. I re-wrote code base to reflect such changes and generating such information instantly.

Thanks go to @jixunmoe with his project https://github.com/jixunmoe/meross-login getting me in the right direction.

v2.0.0 of this project is published now requiring the Meross key instead of message id, sign/token and timestamp (see ReadMe.md).

**Comment by peterchs** [comment]
About to post the same :)  Had updated fw on my devices and they stopped working with the replayed timestamp/sign/message ids.  Had hacked a version using sign generated from md5(messageId + key + timestamp) and generated other values rather than static, was working.

Will test 2.0.0.

**Comment by peterchs** [comment]
Confirm 2.0.0 working for my devices (MSS210 mini and MSS210 large/regular, both running latest firmware [latest firmware had previously broken 1.x module using static values]).
