### ISSUE TITLE
MSS210 not working

### ISSUE THREAD

**Issue by osperling** [dehsgr/node-red-contrib-meross#15]
As stated in the documentation I installed Fiddler, set it up as a proxy on my iOS phone and used the Meross app to turn on/off my smart plug. After doing that I got the following information about my device.

"header": {
    "messageId": "ae3d06a66666dcaa248a3ed45530d756",
    "method": "SET",
    "from": "http://192.168.0.87/config",
    "payloadVersion": 1,
    "namespace": "Appliance.Control.ToggleX",
    "uuid": "2101153644851690839348e1e94600bd",
    "sign": "7e6465d4f0f67e8f1b7dac0442b87bf1",
    "triggerSrc": "iOSLocal",
    "timestamp": 1631995006
  }

After that I installed the Meross plugin and set up a flow using the example JSON.
I configured the Meross smart plug node with the information given above. 

![Bildschirmfoto 2021-09-18 um 22 13 09](https://user-images.githubusercontent.com/42543244/133907381-03b30775-017b-4ec5-9f1f-8a658ee8b290.png)
![Bildschirmfoto 2021-09-18 um 22 12 51](https://user-images.githubusercontent.com/42543244/133907382-a65856b0-666d-4d8b-a7f7-baa1bbfb167a.png)

Now I keep getting this error.

![Bildschirmfoto 2021-09-18 um 22 01 32](https://user-images.githubusercontent.com/42543244/133907331-2633a076-fbc7-4f78-9632-4587d368e38f.png)

**Comment by peterchs** [comment]
Same behaviour as #13.  I expect you have a MSS210 mini or a newer firmware MSS210 which is particular about the content length header, same as my MSS210 mini.

I have raised a PR which will probably resolve.

To manually apply this fix download the smartplug-control.js file from here:
https://github.com/peteakalad/node-red-contrib-meross/raw/main/meross/smartplug-control.js

Overwriting the same file located in your node red node modules dir, something like this path for the user which is running the nodered service:
~/.node-red/node_modules/node-red-contrib-meross/meross
And restart node red

.. or alternatively await @dehsgr to review my PR and consider merging

**Comment by osperling** [comment]
Thank you very much. That fixed my problem!

**Comment by dehsgr** [comment]
Published new version to NPM.

**Comment by dehsgr** [comment]
There were heavy changes within API resulting in static message ids, sign tokens and timestamp not being accepted anymore. I re-wrote code base to reflect such changes and generating such information instantly.

Thanks go to @jixunmoe with his project https://github.com/jixunmoe/meross-login getting me in the right direction.

v2.0.0 of this project is published now requiring the Meross key instead of message id, sign/token and timestamp (see ReadMe.md).
