### ISSUE TITLE
msg100 also not working

### ISSUE THREAD

**Issue by kuntnedguat** [dehsgr/node-red-contrib-meross#16]
So i Setup my msg100 but i keep getting this error: 
![image](https://user-images.githubusercontent.com/74511875/134088488-e9464bc0-e617-4ad7-919b-af6e78a6d777.png)

**Comment by dehsgr** [comment]
For now see #15 and #13. I‘ll take a look on this later.

**Comment by peterchs** [comment]
Instructions for manually checking my PR fix for the MSG100 refer to my comment on #15 but copy smartgarage-control.js as well from my repo:

https://github.com/dehsgr/node-red-contrib-meross/issues/15#issuecomment-922370511

@kuntnedguat good if you could test it as I’d made the same fix for garage doors assuming they would be changed in a similar way, but that is not yet tested (I only have mss210 plugs, mini and normal).

**Comment by dehsgr** [comment]
Published new version to NPM.

**Comment by kuntnedguat** [comment]
WOW that was fast thanks :) 

i updated and restared Node Red but theres still this error 
![image](https://user-images.githubusercontent.com/74511875/134246326-f353c924-2a63-4ebc-b92f-b56ee3eb3aff.png)

Maybe my config is wrong. 

Should the sign and messageid change with every request?

i also try this :
![image](https://user-images.githubusercontent.com/74511875/134249540-590ff892-b244-4424-a419-19b613b805a5.png)

**Comment by dehsgr** [comment]
No. General data such as sign shouldn‘t change here. I think, I might have found an issue in my fix resulting in a wrong Content-Length being calculated. I‘ll check that out.

I estimate you are from Germany. Am I right? If yes and you‘re accept I would like you to send me a direct mail to [my nickname [at] outlook dot com]. So we might get a better debugging possibility, as I don‘t have an affected device.

**Comment by dehsgr** [comment]
There were heavy changes within API resulting in static message ids, sign tokens and timestamp not being accepted anymore. I re-wrote code base to reflect such changes and generating such information instantly.

Thanks go to @jixunmoe with his project https://github.com/jixunmoe/meross-login getting me in the right direction.

v2.0.0 of this project is published now requiring the Meross key instead of message id, sign/token and timestamp (see ReadMe.md).

**Comment by kuntnedguat** [comment]
Nicht ganz ich bin aus der Schweiz :). Danke für den schnellen Support. Jetzt funktionierts.
