### ISSUE TITLE
Opposite of an issue - does more than expected ;)

### ISSUE THREAD

**Issue by koshisan** [dehsgr/node-red-contrib-meross#17]
Hi, I just wanted to let you know you can add the MSS425 to the list of supported devices!

https://www.amazon.co.jp/-/en/MSS425JP-plug/dp/B07Q74QWDB?pd_rd_w=Q7Tm2&pf_rd_p=fe0ec30a-fda5-41ca-ac8e-98048a7d7bc5&pf_rd_r=PJN7KSYF19KQSJWCYJSJ&pd_rd_r=4f250dd9-7943-4cd0-8756-06521190adb6&pd_rd_wg=lmWNt&pd_rd_i=B07Q74QWDB&psc=1&ref_=pd_bap_d_rp_1_t

It works as the other plugs - both USB ports are on channel 4

Thanks for your great work!

Jens

**Comment by dehsgr** [comment]
Thank you very much for reporting this enhancement. I just added it to ReadMe.
