### ISSUE TITLE
INFO: How to get the key using Homeassistant

### ISSUE THREAD

**Issue by guenter-ms** [dehsgr/node-red-contrib-meross#18]
Hello,

another easy way is to use a Homeassistant installation https://www.home-assistant.io/ with HomeKit-Controller Integration

1. reset the devices (press button on device >5 seconds)
2. start Homekit-Controller integration  https://www.home-assistant.io/integrations/homekit_controller/ (press "ADD INTEGRATION" Button
3. pair the device (follow  the popup)
4. find the key from /config/.storage/core.device_registry dataset
5. search for "Meross" and the wanted key is the "id", see below:
       "manufacturer": "Meross",
                "model": "MSS210",
                "name": "MSS210-5af9",
                "sw_version": "4.1.9",
                "entry_type": null,
                "id": "**327723xxxxxxxxxxxxxxxx688**",
                "via_device_id": null,
                "area_id": null,
                "name_by_user": null,
                "disabled_by": null,
                "configuration_url": null
6. Add to apple Homekit Home App, if you like to use SIRI. That works parallel to Nodered. 

Good luck

**Comment by dehsgr** [comment]
Thanks for this information!
