### ISSUE TITLE
Feature Request: Get state when plug is switched manually or by SIRI 

### ISSUE THREAD

**Issue by guenter-ms** [dehsgr/node-red-contrib-meross#19]
Hello,

the Nodered implementation is very good, but only oneway out. When the state of the unit is changed by the local button or the apple Home App or SIRI, the node does not output that change as an event.

That would be very helpful to update the dashboard, when state has changed, to prevent from polling the device often, to see changes.

Thank you.

**Comment by dehsgr** [comment]
Using the right nodes there is no need to poll the state frequently. E.g. you might use redmatic-homekit nodes to accomplish state changes from and to HomeKit:

`[{"id":"132f2560.410c23","type":"redmatic-homekit-universal","z":"9e75ae4f.7f9cf","g":"fc11753.de3a788","bridgeConfig":"95aa15d5.582478","name":"SmartPlug","services":[{"subtype":"0","service":"Outlet","name":"SmartPlug"}],"x":540,"y":280,"wires":[["153377da.a99b98"]]},{"id":"153377da.a99b98","type":"smartplug-control","z":"9e75ae4f.7f9cf","g":"fc11753.de3a788","confignode":"d9dc372f.d15f08","name":"SmartPlug","ip":"0.0.0.0","x":540,"y":320,"wires":[["adfb23df.9881f","132f2560.410c23"]]},{"id":"95aa15d5.582478","type":"redmatic-homekit-bridge","name":"RedMatic Bridge","username":"00:00:00:00:00:00","pincode":"123-45-678","port":"12345"},{"id":"d9dc372f.d15f08","type":"meross-config","name":"Meross","key":"abcdef0123456789abcdef0123456789"}]`

**Comment by guenter-ms** [comment]
Thank you! But I didn't get it work to read state messages from state changes
Q1: Which Bridge is to configure in Universal Node?
Q2: What Name is to configure in Universal Mode (output field)?
Q3: I have coupled the plug direct to the Home App (without a bridge) to avoid pseudo devices. How can I connect the Universal node?
Thanks!

**Comment by dehsgr** [comment]
Well, directly from within HomKit there is no possibility to get devices state. This would only be possible while publishing smart plug as described above. So you would create a HomeKit bridge from within node-red. This is documented very well at https://github.com/rdmtc/RedMatic-HomeKit.
