### ISSUE TITLE
How to get a Token and Timestamp out of Wireshark

### ISSUE THREAD

**Issue by cajoma** [dehsgr/node-red-contrib-meross#2]

**Comment by cajoma** [comment]
Can someone provide a description how to:  "It's requiring a Merross token and a corresponding timestamp to be provided by you. You should get this data via network sniffer or traffic interception between your Meross app and your Smart Plug."

Thank you

**Comment by dehsgr** [comment]
1. You might download [Fiddler](https://www.telerik.com/fiddler).
2. Configure it to capture HTTPS traffic.
3. Transfer Fiddlers HTTPS certificate to your phone and trust it there.
4. Configure your phone to use Fiddler as proxy according to your configuration.
5. Capture traffic while changing your smart plug state with Meross app.

Now you should see a request in Fiddle like "http://yourip/config" with type "POST".

6. Select that request and switch over to "request" body tab.
7. Change format for the request body to "JSON".

This should look like:
<pre>{
  "payload": {},
  "header": {
    "messageId": "1234567890abcdef1234567890abcdef",
    "method": "GET",
    "from": "http://yourip/config",
    "sign": "567890abcdef1234567890abcdef12345678",
    "namespace": "Appliance.System.Ability",
    "triggerSrc": "iOSLocal",
    "timestamp": 1609232320,
    "payloadVersion": 1
  }
}
</pre>

The token is the value from „sign“. The corresponding timestamp is the value from „timestamp“. The message id is the value from „messageid“.
