### ISSUE TITLE
"Smart Roller Shutter Timer" - There was an Error: Error: socket hang up

### ISSUE THREAD

**Issue by MazoSergey** [dehsgr/node-red-contrib-meross#21]
Hello!

Could you help me please with an issue I have.  According to your manual I've got the key, I am trying to push "true" to the Roller Shutter and what I get is "There was an Error: Error: socket hang up" :(

Detailes about the device I have:

        {
            "uuid": "XXX",
            "onlineStatus": 1,
            "devName": "Smart Roller Shutter Timer",
            "devIconId": "device063_eu",
            "bindTime": 1658685622,
            "deviceType": "mrs100",
            "subType": "eu",
            "channels": [
                {}
            ],
            "region": "eu",
            "fmwareVersion": "7.6.6",
            "hdwareVersion": "7.0.0",
            "userDevIcon": "",
            "iconType": 1,
            "skillNumber": "",
            "cluster": 2,
            "domain": "mqtt-eu-2.meross.com",
            "reservedDomain": "mqtt-eu-2.meross.com"
        }

Thank you in advance!

**Comment by dehsgr** [comment]
Sorry. This device is not supported.
