### ISSUE TITLE
No LED update after firmware update (MSS310)

### ISSUE THREAD

**Issue by bendenoz** [dehsgr/node-red-contrib-meross#24]
After updating the firmware last week, the device can still be controlled but the LED does not change anymore.
I have also been seing occasional "Error: socket hang up" errors

After sniffing the local network (see trace below) and doing some testing, it looks like the `triggerSrc` header is now required. When it is included the LED updates properly. The Meross app sends `"AndroidLocal` but it looks like any value will work

  

Traced command from latest app :
```json
{
  "header": {
    "from": "/app/*******-********************************/subscribe",
    "messageId": "f0a5479a510c4a4326a8cee63f42590a",
    "method": "SET",
    "namespace": "Appliance.Control.ToggleX",
    "payloadVersion": 1,
    "sign": "7381ef30715d3032d7b9fe74b02a5a4f",
    "timestamp": 1670771354,
    "triggerSrc": "AndroidLocal",
    "uuid": "********************************"
  },
  "payload": {
    "togglex": {
      "channel": 0,
      "onoff": 1
    }
  }
}
```

**Comment by dehsgr** [comment]
Thanks for reporting and your work to provide the solution directly, @bendenoz. I really appreciated it!

**Comment by bendenoz** [comment]
no pb thanks for the fast update!
