### ISSUE TITLE
[SUGGESTION] Add Original Message in Our message

### ISSUE THREAD

**Issue by emme73** [dehsgr/node-red-contrib-meross#25]
Ciao,
it would be nice to include the input message in the output one, specially in multichannels surge protectors the output message just include a payload but not the channel.

I've made it by changinging line 85 of smartplug-control.js 
from
Platform.send({ payload : r });
 to
Platform.send({ origin: msg, payload : r });

**Comment by dehsgr** [comment]
Thanks for your input. A new version is published ASAP.
