### ISSUE TITLE
Control Multiple Plugs with one node

### ISSUE THREAD

**Issue by SC-Syndikat** [dehsgr/node-red-contrib-meross#29]
Hi and first of all: 
Great work. Thank you very much.

Is it possible to inject the ip of the plug via payload such that I don't have to create a node for each of my smart plugs?

I tried configuring the node with "{{msg.ip}}" in the IP property but it results in this error:
"There was an Error: Error: Invalid URI "http:///%7B%7Bmsg.ip%7D%7D/config""

**Comment by dehsgr** [comment]
@SC-Syndikat no, this isn't expected. You must create a node for each smart plug.
