### ISSUE TITLE
No issue - looking for advice...

### ISSUE THREAD

**Issue by PentlandIT** [dehsgr/node-red-contrib-meross#6]
Hi there,

Could you elaborate on the process of sniffing for the right packets to get the additional information to integrate locally?

I didn't see a discussion active on this Github page so thought to reach out via an issue.

Thanks in advance.

**Comment by PentlandIT** [comment]
Closing ticket as I see a very similar close issue raised.

**Comment by dehsgr** [comment]
Discussed in #2.
