### ISSUE TITLE
MSG200 GarageDoor opener - their new product

### ISSUE THREAD

**Issue by Tsepatek** [dehsgr/node-red-contrib-meross#9]
Hi again,
I am not much of a coder, but I was able to set Fiddler to sniff the network traffic between Meross and my Android phone.
Please, help me and upgrade your code to support MSG200 too.
I can be the QA tester :)

Here is what I got:
{"header":
{"messageId":"46b83eaf52d003abe292ce257b7d1111",
"namespace":"Appliance.System.All",
"triggerSrc":"AndroidLocal",
"method":"GETACK",
"payloadVersion":1,
"from":"/appliance/2012151516760790836648e1e9411111/publish",
"timestamp":1612963597,
"timestampMs":565,
"sign":"b3ccde092559f045b2243c4bdabc2a6c"},
"payload":
{"all":{"system":{"hardware":{"type":"msg200","subType":"us","version":"4.0.0","chipType":"MT7686","uuid":"2012151516760790836648e1e9111111","macAddress":"45:e1:e9:51:08:51"},"firmware":{"version":"4.1.3","homekitVersion":"2.0.1","compileTime":"Oct 31 2020 10:47:37","wifiMac":"12:e8:22:c4:eb:a3","innerIp":"192.168.8.222","server":"mqtt.meross.com","port":443,"userId":1172111},"time":{"timestamp":1612963597,"timezone":"Europe/Helsinki","timeRule":[[1603587600,7200,0],[1616893200,10800,1],[1635642000,7200,0],[1648342800,10800,1],[1667091600,7200,0],[1679792400,10800,1],[1698541200,7200,0],[1711846800,10800,1],[1729990800,7200,0],[1743296400,10800,1],[1761440400,7200,0],[1774746000,10800,1],[1792890000,7200,0],[1806195600,10800,1],[1824944400,7200,0],[1837645200,10800,1],[1856394000,7200,0],[1869094800,10800,1],[1887843600,7200,0],[1901149200,10800,1]]},"online":{"status":1,"bindId":"qKiVq3AR9WTbE3t4","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":0},{"channel":1,"onoff":0,"lmTime":0},{"channel":2,"onoff":0,"lmTime":0},{"channel":3,"onoff":0,"lmTime":0}],"triggerx":[{"channel":1,"id":"2222222222222222","count":1},{"channel":2,"id":"3333333333333333","count":1},{"channel":3,"id":"4444444444444444","count":1}],"timerx":[],"garageDoor":[{"channel":1,"open":1,"lmTime":0},{"channel":2,"open":1,"lmTime":0},{"channel":3,"open":1,"lmTime":0}]}}}}

Best Regards,
Toni

**Comment by dehsgr** [comment]
Hi Toni,

did you already tried Garage Door node?

**Comment by Tsepatek** [comment]
> Hi Toni,
> 
> did you already tried Garage Door node?

Yes, I did. I tried to send boolean payload true and false. msg.payload = true, msg.payload = false.
In this new device there is 3 connections/channels so you can add 3 door sensors. I think that got something to do with it that sending true or false is not enough.

**Comment by dehsgr** [comment]
Ah, okay. I see. I try to change sth. and get back to you.

**Comment by dehsgr** [comment]
@Tsepatek can you override smartgarage-control.js and smartgarage-control.html within you installation with the latest changes from this repository and check, if you're able to set 0-based channel and trigger your garage door accordingly?

**Comment by Tsepatek** [comment]
Hi,
Yes, I can. I'll let you know as soon as I have tested it.

**Comment by Tsepatek** [comment]
Hi again,
Did you updated the smartgarage-control.js code, because it is exactly the same as before?

**Comment by dehsgr** [comment]
@Tsepatek yes, of course I did. e.g. Line 12 should have changed to `this.channel = myNode.channel;`.

**Comment by Tsepatek** [comment]
Ok, I have tested it but it does not open or close the door. My garage door's magnetic sensor is in channel 1.

**Comment by dehsgr** [comment]
Okay. So I would like you to sniff a full sniff/trace of opening and closing your door from your meross app. You might send it to mynickname@outlook.com. Did you try IDs 0-2? Did you get some status back when requesting status and sending it to a debug node?

**Comment by Tsepatek** [comment]
Hi,
I tried true/false, 0/1 but nothing happened.
Then I sent timestamp payload and got errors below.

2/11/2021, 6:21:39 PMnode: 7e0a3746.159f48
msg.payload : string[25]
"Received unexpected data!"
2/11/2021, 6:21:39 PMnode: c6dca7ec.908a08
msg.payload : boolean
false

I will sniff the network tomorrow and get back to you as soon as I get some results.

**Comment by Tsepatek** [comment]
Hi,
I decided to sniff the network today. I have sent you the result to your outlook.com account.
Best Regards,
Tsepatek

**Comment by dehsgr** [comment]
Thanks for sending sniffed data. To complete I would like to move over here. So you wrote via mail:
> Hi,
> I managed to get it work by replacing the Platform.channel with value 1.
> From where the code gets the value to the Platform.channel?
>  
> Best Regards,
> Tsepatek

I'm pleased that you got it working, setting channel to 1. This setting you would do within the node itself. Maybe some caching was preventing display of this new field. I would like you to check this again and finally give your feedback.

So with your confirmation I'll publish another version to NPM then to make this new feature public.

Thank you very much for working together!

**Comment by dehsgr** [comment]
@STDevMan you might merge these new changes to your fork.

**Comment by Tsepatek** [comment]
Thank you for your quick answers and coding help. It was my pleasure to help you.
Now I am able to control my Garage Door with Node-Red and set alarms if it is opened.

**Comment by dehsgr** [comment]
@Tsepatek did you find the new node field?

[Cross-referencing #7.]

**Comment by dehsgr** [comment]
I could finally confirm new field. So I'm closing here. NPM publish done.

**Comment by Tsepatek** [comment]
Yes, I found it and the node is working fine. Only thing is that sending timestamp gives true all the time, so the door status cannot be checked.

**Comment by dehsgr** [comment]
You might send me another to sniffs from Meross app (close app first to get it requesting garage door state):
- One with door open.
- One with door closed.

This shouldn't be a problem to get this fixed too. ;-)

**Comment by dehsgr** [comment]
@Tsepatek I found the bug. I wasn't converting the index correctly into a number. Latest publish should work for you.

**Comment by Tsepatek** [comment]
Hi,
I just sent you the sniffing results. I will test the latest code. Thanks

**Comment by dehsgr** [comment]
You might have to correct channel index now. Thanks again for bringing this forward.

**Comment by STDevMan** [comment]
nice work guys. I've been super busy recently. Looks like you got a couple updates to the code recently. super cool
